include config.mk
ifeq ($(USE_YARAX),1)
CFLAGS+=USE_YARAX=1
YARADEP=yara-x/target/release/libyara_x.rlib
else
YARADEP=
endif

all clean user-install install symstall user-uninstall uninstall: $(YARADEP)
	$(MAKE) -C src $@

ifeq ($(USE_YARAX),1)
yara-x/target/release/libyara_x.rlib:
	$(MAKE) yarax
endif

mrproper: clean
	rm -f config.mk

yarax: yara-x
	cd yara-x && cargo build -r
	cd yara-x/capi && cargo build -r

yara-x:
	git clone https://github.com/VirusTotal/yara-x

RULESDIR=$(R2PM_USRPLUGIN_DIR)/rules-yara3
